# Generated by Django 5.1.6 on 2026-04-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("samples", "0002_apksample_is_valid_apk_apksample_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShellDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shell_type",
                    models.CharField(blank=True, default="UNKNOWN", max_length=128),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence", models.TextField(blank=True, default="")),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("NO_UNPACK", "无需脱壳"),
                            ("BLACKDEX", "BlackDex"),
                            ("FRIDA", "Frida"),
                            ("BLACKDEX_THEN_FRIDA", "BlackDex 后 Frida"),
                            ("MANUAL_REVIEW", "人工复核"),
                        ],
                        default="BLACKDEX_THEN_FRIDA",
                        max_length=32,
                    ),
                ),
                ("raw_output", models.JSONField(blank=True, default=dict)),
                ("command", models.CharField(blank=True, default="", max_length=255)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shell_detections",
                        to="samples.apksample",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shell_type"], name="shell_detec_shell_t_378ad1_idx"
                    ),
                    models.Index(
                        fields=["strategy"], name="shell_detec_strateg_1b0304_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="shell_detec_created_1faea7_idx"
                    ),
                ],
            },
        ),
    ]
