# Generated by Django 5.1.6 on 2026-04-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("samples", "0002_apksample_is_valid_apk_apksample_updated_at_and_more"),
        ("shell_detector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnpackJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("QUEUED", "已入队"),
                            ("IDENTIFYING_SHELL", "识壳中"),
                            ("SELECTING_STRATEGY", "选择策略"),
                            ("STARTING_EMULATOR", "启动模拟器"),
                            ("INSTALLING_APK", "安装APK"),
                            ("RUNNING_BLACKDEX", "运行BlackDex"),
                            ("RUNNING_FRIDA", "运行Frida"),
                            ("COLLECTING_ARTIFACTS", "收集产物"),
                            ("SUCCESS", "成功"),
                            ("PARTIAL_SUCCESS", "部分成功"),
                            ("FAILED", "失败"),
                            ("REVIEW_REQUIRED", "人工复核"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("NO_UNPACK", "无需脱壳"),
                            ("BLACKDEX", "BlackDex"),
                            ("FRIDA", "Frida"),
                            ("BLACKDEX_THEN_FRIDA", "BlackDex 后 Frida"),
                            ("MANUAL_REVIEW", "人工复核"),
                        ],
                        default="BLACKDEX_THEN_FRIDA",
                        max_length=32,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "artifact_dir",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("artifact_paths", models.JSONField(blank=True, default=list)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("requires_review", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unpack_jobs",
                        to="samples.apksample",
                    ),
                ),
                (
                    "shell_detection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unpack_jobs",
                        to="shell_detector.shelldetectionresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=64)),
                ("level", models.CharField(default="INFO", max_length=16)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="unpack_tasks.unpackjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="unpackjob",
            index=models.Index(fields=["status"], name="unpack_task_status_528ecb_idx"),
        ),
        migrations.AddIndex(
            model_name="unpackjob",
            index=models.Index(
                fields=["strategy"], name="unpack_task_strateg_f7a56f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unpackjob",
            index=models.Index(
                fields=["created_at"], name="unpack_task_created_8d28fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(fields=["stage"], name="unpack_task_stage_5ba23a_idx"),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(fields=["level"], name="unpack_task_level_3a1d8a_idx"),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(
                fields=["created_at"], name="unpack_task_created_def2a2_idx"
            ),
        ),
    ]
