# Generated by Django 5.1.6 on 2026-04-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnpackTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待执行"),
                            ("VALIDATING", "校验中"),
                            ("IDENTIFYING_SHELL", "识壳中"),
                            ("STRATEGY_SELECTED", "策略已选择"),
                            ("RUNNING_UNPACK", "脱壳中"),
                            ("REVIEW_REQUIRED", "待人工复核"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLACKDEX", "BlackDex"),
                            ("FRIDA", "Frida"),
                            ("HYBRID", "Hybrid"),
                            ("MANUAL", "Manual"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "shell_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("shell_report", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("requires_manual_review", models.BooleanField(default=False)),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "result_artifact",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("context_json", models.JSONField(blank=True, default=dict)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="samples.apksample",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待执行"),
                            ("VALIDATING", "校验中"),
                            ("IDENTIFYING_SHELL", "识壳中"),
                            ("STRATEGY_SELECTED", "策略已选择"),
                            ("RUNNING_UNPACK", "脱壳中"),
                            ("REVIEW_REQUIRED", "待人工复核"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analysis.unpacktask",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="unpacktask",
            index=models.Index(fields=["status"], name="analysis_un_status_231cd7_idx"),
        ),
        migrations.AddIndex(
            model_name="unpacktask",
            index=models.Index(
                fields=["strategy"], name="analysis_un_strateg_38b278_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unpacktask",
            index=models.Index(
                fields=["created_at"], name="analysis_un_created_282ffc_idx"
            ),
        ),
    ]
