# Generated by Django 5.1.6 on 2026-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APKSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="apks/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                (
                    "package_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "version_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "version_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["sha256"], name="samples_apk_sha256_68a52d_idx"
                    ),
                    models.Index(
                        fields=["package_name"], name="samples_apk_package_6bb837_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="samples_apk_uploade_100eb5_idx"
                    ),
                ],
            },
        ),
    ]
