# Generated by Django 5.1.6 on 2026-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apksample",
            name="is_valid_apk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apksample",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="apksample",
            name="validation_errors",
            field=models.TextField(blank=True, default=""),
        ),
    ]
